### ISSUE TITLE
Styling the input using a label to catch the click

### ISSUE THREAD

**Issue by maxpaj** [deiwin/ngImageInputWithPreview#6]
Hi!

I've recently started using this, but found it difficult to style the input. The usual way of "styling" a file-input nowadays seems to put a label on top which catches the click, but this doesn't work for the input field I've used this directive on...

**Comment by deiwin** [comment]
Hi. Are you certain that this directive is the culprit? Does the file browser open correctly when you remove the directive's attribute from your `input` tag?
