### ISSUE TITLE
Get filename

### ISSUE THREAD

**Issue by condereis** [deiwin/ngImageInputWithPreview#7]
How can i get the filename?

**Comment by deiwin** [comment]
There's no explicit support, but you _could_ get it with `myForm.myImage.$viewValue.name` given this HTML (taken from the demo):
```html
<form name="myForm">
  <tt>myForm.myImage.$viewValue.name = {{myForm.myImage.$viewValue.name}}</tt>
  <input type="file" name="myImage" image-with-preview ng-model="image">
</form>
```

**Comment by Jarvvski** [comment]
Without wanting to necro, the above is how I've gotten the filename. 

@deiwin perhaps we can close this issues?

**Comment by deiwin** [comment]
I guess so. I'll re-open if people feel the above is not sufficient.
