### ISSUE TITLE
0.0.6 is not on npm

### ISSUE THREAD

**Issue by krokofant** [deiwin/ngImageInputWithPreview#9]
https://www.npmjs.com/package/ng-image-input-with-preview?activeTab=versions

**Comment by deiwin** [comment]
I published 0.07, but the publish behaved kind of weird. Can you confirm it works for you?

**Comment by deiwin** [comment]
Published 0.0.6 as well.

**Comment by krokofant** [comment]
Are the only changes on 0.0.7 to the readme?

It's looks a bit weird on npm since the 0.0.6 was published after the 0.0.7 version. Maybe this causes a problem? 0.0.6 is marked as latest even though you've published 0.0.7.

**Comment by deiwin** [comment]
From [the docs](https://docs.npmjs.com/cli/dist-tag):

> By default, npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag.

So yeah, that might be an issue. There's also https://github.com/deiwin/ngImageInputWithPreview/commit/25145a247edcd5ad89d0ff5883ac0a2d7539d825 and https://github.com/deiwin/ngImageInputWithPreview/commit/ade7c2d4cf5d598b6cf61659a0cca27a772e7602 in addition to test and README changes in 0.0.7.

I tried fixing the tag, but `npm dist-tag` doesn't want to play ball. I'll just release 0.0.8. It'll be just the same as 0.0.7, but with the latest tag. Not the prettiest solution, but it'll work.
